### PR TITLE
suppress warnings + upgrade dlib 19.18

### PR DESCRIPTION
**Pull request by fmessmer**
includes #103 
needs https://github.com/ipa320/thirdparty/pull/14

### CODE REVIEW

**Comment by fmessmer** [comment]
@ipa-rmb @ipa-foj @ipa-fog @ipa-jcl
please check whether the new dlib version works for you - or let me know that you need more time....otherwise, I will merge before christmas....

**Comment by jabbenseth** [comment]
:+1: I appreciate pushing a little bit, even though I cannot contribute in this case

**Comment by ipa-foj** [comment]
In principle I would also support a newer version of Dlib. One issue though: In this setting Dlib is build as a static library without the -fPIC option, so you can not use it to build a shared library of the code that uses it (to my knowledge). Would it be better to build it in a shared library or to keep it like that and switch every following library to a static one?

**Comment by fmessmer** [comment]
@ipa-foj 
I did not change anything in the way this library is built
If you want to add something, please feel free to propose a PR to my feature branch
As we do not use this library (just the warnings annoyed me), I cannot say much about that kind of stuff...

**Comment by ipa-foj** [comment]
After testing it turned out that if Dlib is built in Release configuration it is not possible anymore to build depending packages in Debug mode. With overlaying workspaces to not build everything every time this is a little impractical while developing, so please don't merge for now until I found a workaround.

**Comment by fmessmer** [comment]
@ipa-foj any progress on your investigations?

**Comment by ipa-foj** [comment]
I didn't have time this week, I will do it next week though. Sorry for the delay...

**Comment by ipa-foj** [comment]
On my system it looks like version 19.9 is also getting rid of all the warning (when including your changes). I already use 19.9 in my code, so if you switch to that version I would agree to this pull request.

**Comment by fmessmer** [comment]
@ipa-foj 19.9 is added in https://github.com/ipa320/cob_extern/pull/106
please test!

**Pull request closed without merging**
