### PR TITLE
added melodic checks, removed indigo checks, deactivated qsopt

### PR DESCRIPTION
**Pull request by ipa-rmb**
Follows discussions in #96 and #97.

### CODE REVIEW

**Review by ipa-owner-jba — APPROVED** [review]

**Comment by ipa-rmb** [comment]
Do not merge yet, we will wait for the reply of @ipa-foj as discussed in #96 .

**Comment by christian-rauch** [comment]
Could we go forward with this PR as a workaround for `melodic` until the qsopt integration is properly solved?

**Comment by ipa-rmb** [comment]
@ipa-foj What is your preferred way w.r.t. #96 ?

**Comment by ipa-foj** [comment]
As pointed in #96 I think excluding Qsopt and Concorde from this repo is the preferrable way.

**Comment by ipa-rmb** [comment]
@fmessmer would you agree with Florians proposal? As far as we know is there no other user of these libs than us. So we would move them into a new repository and they could be deleted in the new branch of cob_extern.

**Comment by christian-rauch** [comment]
What is the status of this PR? Can `libconcorde_tsp_solver` and `libqsopt` removed from this repo?

**Pull request closed without merging**
