### PR TITLE
Update to latest version of libphidgets

### PR DESCRIPTION
**Pull request by sevenbitbyte**
I've updated the package to use the most recent version of the libphidgets c/c++ library and have tested successfully on ROS Jade.

### CODE REVIEW

**Comment by floweisshardt** [comment]
@ipa-bnm can you test this please

**Comment by sevenbitbyte** [comment]
@ipa-fmw Please let me know if there is anything I can do to enable timely testing

**Comment by benmaidel** [comment]
Tested the PR on raw. Looks good. Nothing to complain.
@ipa-fmw @ipa-fxm we can merge this

**Comment by fmessmer** [comment]
as @ipa-bnm reviewed and confirmed...I'll merge...thanks for the contribution!

**Pull request merged**
