### PR TITLE
Multi distro travis

### PR DESCRIPTION
**Pull request by fmessmer**
replaces #77 

tested CI locally: OK

`ipa320/kinetic_dev` branch should be removed after merge!
(see https://github.com/ipa320/cob_extern/compare/indigo_dev...kinetic_dev)
the libpcan-update has been backported to indigo_dev in #78

### CODE REVIEW

**Comment by fmessmer** [comment]
need to take care of @ipa-mdl's suggestions https://github.com/ipa320/cob_people_perception/pull/56#issuecomment-281200678

**Comment by fmessmer** [comment]
also consider https://github.com/ipa320/cob_driver/pull/323#issuecomment-284230720

**Comment by fmessmer** [comment]
we'll need to incorporate changes from #81 and refactor the other packages similarly

**Comment by fmessmer** [comment]
Travis succeeds, however, I see the following warning for all packages:
```
catkin_package() DEPENDS on 'EP_libpcan' but neither

  'EP_libpcan_INCLUDE_DIRS' nor 'EP_libpcan_LIBRARIES' is defined.
```

@ipa-mdl something we need to worry about/can fix?

**Comment by ipa-fxm** [comment]
Travis succeeds, however, I see the following warning for all packages:
```
catkin_package() DEPENDS on 'EP_libpcan' but neither

  'EP_libpcan_INCLUDE_DIRS' nor 'EP_libpcan_LIBRARIES' is defined.
```

@ipa-mdl something we need to worry about/can fix?

**Comment by mathias-luedtke** [comment]
> something we need to worry about/can fix?

Yes, this is wrong.
`EXPORTED_TARGETS EP_${PROJECT_NAME}` should be used.

**Comment by fmessmer** [comment]
`EXPORTED_TARGETS` solved the issue

**Review by NadiaHG — APPROVED** [review]
I trust Travis, didn't review each CMakeLists file

**Pull request merged**
