### PR TITLE
update to peak driver version 8.3

### PR DESCRIPTION
**Pull request by benmaidel**
this should fix the asm/linkage.h error. See https://github.com/ipa320/cob_extern/issues/71

### CODE REVIEW

**Comment by fmessmer** [comment]
Visual Review looks good...I don't have a setup to actually test it.

@tobiasneumann can you verify whether this fixes your issue #71?

**Comment by benmaidel** [comment]
@ipa-flg and me tested it on raw3-3. With this update it works fine on newer kernel versions

**Review by floweisshardt — APPROVED** [review]

**Comment by benmaidel** [comment]
@ipa-fxm please approve if ok from your side

**Comment by benmaidel** [comment]
Tested on several machines.
indigo: ok
kinetic: ok

will merge it

**Comment by fmessmer** [comment]
> indigo: ok

So, should we cherry-pick to `indigo_dev`?
This would supersede https://github.com/ipa320/cob_extern/pull/56, right?

**Pull request merged**
