### PR TITLE
Indigo release candidate

### PR DESCRIPTION
**Pull request by floweisshardt**

### CODE REVIEW

**Review by mgruhler — CHANGES_REQUESTED** [review]
There seems to be something off with the change logs.

There is no order within the 0.6.x tags. Also, 0.6.7 is shown as a seperate commit, even though this has been release, but 0.6.8 has never been released?  (https://github.com/ros/rosdistro/pulls?utf8=%E2%9C%93&q=is%3Apr%20cob_extern)

**Comment by floweisshardt** [comment]
0.6.8 was a temp release and was substituted by 0.6.9 some minutes later.

We're using the tools `catkin_generate_changelog` and `catkin_prepare_release`, no idea why the order got confused. I still strugle with changing this manually as it will be procressed (and overwritten) later on again by the release scripts.

**Comment by mgruhler** [comment]
Should we put this up as a question for the OSRF guys? I just find this strange....

**Comment by fmessmer** [comment]
So what are we going to do with this?
Seems like the order of the [CHANGELOG.rst](https://github.com/ipa320/cob_extern/blob/indigo_dev/cob_extern/CHANGELOG.rst) has been messed up on the ```indigo_dev```-branch already - before 0.6.7 was triggered....

**Comment by mgruhler** [comment]
Hmm, would manually adjusting the Changelogs work?

**Comment by fmessmer** [comment]
trying it atm

**Comment by mgruhler** [comment]
great, so I will not do that than ;-) started as well right now :-D

**Comment by fmessmer** [comment]
manually fixed the changelogs in #68, i.e. this PR is superseded

**Pull request closed without merging**
